# Generated by Django 4.2.3 on 2025-10-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_alter_course_id_alter_enrollment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
    ]
